name: CI
on:
  pull_request:
    types: [opened, ready_for_review] # synchronize is specified for check
    branches:
      - main

jobs:
  assign:
    name: Use this action for check
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Use this action
        uses: ./
        id: assign
        with:
          assignees: ${{ github.actor }}
          bot-accounts: some-bot
          reviewers: champ96k
          #max-num-of-reviewers: 2
          draft-keyword: wip
          ready-comment: 'Ready for review :rocket: `<reviewers>`'
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}'
  assign-closed:
    name: Use this action for check [closed]
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Use this action
        uses: hkusu/review-assign-action@master
        id: assign
        with:
          merged-comment: 'It was merged. Thanks for your review :wink: `<reviewers>`'
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}
        
  flutter_test:
    name: Run flutter analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: dart format .

  build_appbundle:
    name: Build Flutter (Android)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle