name: CI
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
    branches:
      - main

jobs: 
  flutter_test:
    name: Run flutter analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  test:
    name: Add Reviewers
    runs-on: macos-latest
    steps:
      - uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: john,kramer,seinfeld
          re-request-when-approved: true
          re-request-when-changes-requested: true
      
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: dart format .

  build_appbundle:
    name: Build Flutter (Android)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle